name: CBD
on:
    push:
        branches:
            - main
jobs:
    cbd:
        name: doc cbd
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Build
              run: npm i && npm run build
            - name: DeployGP
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GIT_TOKEN }}
                  publish_dir: ./docs/.vuepress/dist

            # Runs a single command using the runners shell
            - name: Commit & Push
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add -A .
                  git commit -m "generated"
                  git push
